export const todayQuests = [
  {
    title: "家から外の写真を撮る",
    type: "記録",
    point: 20,
    level: "簡単",
    timer: "5分",
    description: "家の中から、外の風景を1枚写真に撮ってみよう。",
    icon: "🏠",
    category: "photo",
  },
  {
    title: "古い建物を記録する",
    type: "探索",
    point: 80,
    level: "普通",
    timer: "30分",
    description: "地元にある古い建物を探し、写真を撮って記録しよう。",
    icon: "🏛️",
    category: "exploration",
  },
  {
    title: "生き物を発見する",
    type: "自然",
    point: 50,
    level: "簡単",
    timer: "15分",
    description: "身の回りにいる生き物（動物、昆虫など）を1つ見つけて、写真を撮ろう。",
    icon: "🐾",
    category: "nature",
  },
  {
    title: "自然の風景を撮る",
    type: "自然",
    point: 60,
    level: "簡単",
    timer: "20分",
    description: "空、木、水など、自然の風景を1枚写真に収めよう。",
    icon: "🌳",
    category: "nature",
  },
  {
    title: "一番遠いコンビニまで歩く",
    type: "運動",
    point: 120,
    level: "難しい",
    timer: "1時間",
    description: "自宅から一番遠いコンビニまで歩いて、達成感を味わおう。",
    icon: "🚶‍♂️",
    category: "daily",
  },
  {
    title: "夕焼けを撮影する",
    type: "記録",
    point: 70,
    level: "簡単",
    timer: "15分",
    description: "空が一番きれいに染まる時間帯に、夕焼けの写真を撮ろう。",
    icon: "🌇",
    category: "photo",
  },
  {
    title: "家を違う視点から見る",
    type: "探索",
    point: 30,
    level: "簡単",
    timer: "10分",
    description: "普段見ない方向から自分の家を眺め、新しい発見をしてみよう。",
    icon: "🏡",
    category: "exploration",
  },
  {
    title: "地図を比較する",
    type: "学習",
    point: 90,
    level: "普通",
    timer: "45分",
    description: "地元の昔の地図と今の地図を見比べて、街の変化を調べてみよう。",
    icon: "🗺️",
    category: "learning",
  },
  {
    title: "古いお店を探す",
    type: "探索",
    point: 80,
    level: "普通",
    timer: "30分",
    description: "地元で一番古いお店を探してみよう。",
    icon: "🏪",
    category: "exploration",
  },
  {
    title: "お寺や神社の歴史を調べる",
    type: "学習",
    point: 100,
    level: "難しい",
    timer: "1時間",
    description: "古いお寺や神社の写真を撮り、その歴史を調べてみよう。",
    icon: "⛩️",
    category: "learning",
  },
  {
    title: "石碑や記念碑を見つける",
    type: "探索",
    point: 70,
    level: "普通",
    timer: "30分",
    description: "街のどこかにある石碑や記念碑を見つけてみよう。",
    icon: "🗿",
    category: "exploration",
  },
  {
    title: "歴史を感じる建物を撮る",
    type: "記録",
    point: 80,
    level: "普通",
    timer: "40分",
    description: "歴史を感じる建物の写真を撮って、その魅力を再発見しよう。",
    icon: "🏰",
    category: "photo",
  },
  {
    title: "観光地を初訪問する",
    type: "探索",
    point: 110,
    level: "普通",
    timer: "1.5時間",
    description: "地元の有名な観光地を、初めて訪れたつもりで歩いてみよう。",
    icon: "🗼",
    category: "exploration",
  },
  {
    title: "動植物を撮影する",
    type: "自然",
    point: 60,
    level: "簡単",
    timer: "20分",
    description: "街で見かける動物や植物の写真を撮ってみよう。",
    icon: "🐾",
    category: "nature",
  },
  {
    title: "建築物を調べる",
    type: "学習",
    point: 120,
    level: "難しい",
    timer: "1.5時間",
    description: "好きな建築物の写真を撮り、設計者の名前を調べてみよう。",
    icon: "🏗️",
    category: "learning",
  },
  {
    title: "自動販売機を訪れる",
    type: "記録",
    point: 40,
    level: "簡単",
    timer: "10分",
    description: "よく使う自動販売機を訪れて写真を撮り、感謝の気持ちを伝えよう。",
    icon: "🥤",
    category: "photo",
  },
  {
    title: "一番高い建物を探す",
    type: "探索",
    point: 90,
    level: "普通",
    timer: "45分",
    description: "地元で一番高い建物を探して、その写真を撮ってみよう。",
    icon: "🏙️",
    category: "exploration",
  },
  {
    title: "雲の写真を撮る",
    type: "記録",
    point: 30,
    level: "簡単",
    timer: "10分",
    description: "空を見上げて、印象的な雲の写真を撮ってみよう。",
    icon: "☁️",
    category: "photo",
  },
  {
    title: "地域の掲示板を読む",
    type: "学習",
    point: 40,
    level: "簡単",
    timer: "15分",
    description: "地域の掲示板に貼ってあるポスターを読んで、情報を集めよう。",
    icon: "📝",
    category: "learning",
  },
  {
    title: "街の落書きを記録する",
    type: "記録",
    point: 50,
    level: "簡単",
    timer: "20分",
    description: "街で見つけたユニークな落書きの写真を撮ってみよう。",
    icon: "🎨",
    category: "photo",
  },
  {
    title: "地元の名産品を調べる",
    type: "学習",
    point: 60,
    level: "普通",
    timer: "30分",
    description: "地元の名産品や特産品を一つ調べてみよう。",
    icon: "🍊",
    category: "learning",
  },
  {
    title: "一番安いジュースを探す",
    type: "生活",
    point: 40,
    level: "簡単",
    timer: "15分",
    description: "スーパーで一番安いジュースを探し、節約の達人になろう。",
    icon: "💰",
    category: "shopping",
  },
  {
    title: "地元産の野菜を探す",
    type: "生活",
    point: 50,
    level: "簡単",
    timer: "20分",
    description: "スーパーで地元産の野菜や果物を探してみよう。",
    icon: "🥕",
    category: "shopping",
  },
  {
    title: "電話ボックスを探す",
    type: "探索",
    point: 40,
    level: "簡単",
    timer: "15分",
    description: "懐かしい電話ボックスを街で探してみよう。",
    icon: "📞",
    category: "exploration",
  },
  {
    title: "ブランコを漕ぐ",
    type: "運動",
    point: 30,
    level: "簡単",
    timer: "10分",
    description: "公園にあるブランコを漕いで、子どもの頃の気分を味わおう。",
    icon: "🎠",
    category: "daily",
  },
  {
    title: "落ち葉を集める",
    type: "自然",
    point: 40,
    level: "簡単",
    timer: "15分",
    description: "道端にあるきれいな落ち葉を拾って集めてみよう。",
    icon: "🍂",
    category: "nature",
  },
  {
    title: "野草の花を観察する",
    type: "自然",
    point: 50,
    level: "簡単",
    timer: "20分",
    description: "小さな野草の花をじっくり観察してみよう。",
    icon: "🌸",
    category: "nature",
  },
  {
    title: "川や池の写真を撮る",
    type: "自然",
    point: 60,
    level: "簡単",
    timer: "25分",
    description: "地元の川や池の写真を撮り、水辺の風景を記録しよう。",
    icon: "💧",
    category: "nature",
  },
  {
    title: "木の幹に触れる",
    type: "自然",
    point: 30,
    level: "簡単",
    timer: "10分",
    description: "近くにある木の幹に触れて、自然の感触を確かめよう。",
    icon: "🌲",
    category: "nature",
  },
  {
    title: "一番大きな木を探す",
    type: "探索",
    point: 70,
    level: "普通",
    timer: "30分",
    description: "地元で一番大きな木を探して、その迫力を感じてみよう。",
    icon: "🌳",
    category: "exploration",
  },
  {
    title: "鳥の鳴き声を聞く",
    type: "自然",
    point: 30,
    level: "簡単",
    timer: "10分",
    description: "目を閉じて、街の鳥の鳴き声に耳を傾けてみよう。",
    icon: "🐦",
    category: "nature",
  },
  {
    title: "家で一番好きな場所を撮る",
    type: "記録",
    point: 20,
    level: "簡単",
    timer: "5分",
    description: "家の中で一番落ち着く場所や好きな場所を写真に撮ってみよう。",
    icon: "🏠",
    category: "photo",
  },
  {
    title: "犬や猫の写真を撮らせてもらう",
    type: "交流",
    point: 80,
    level: "普通",
    timer: "20分",
    description: "街で見かけた犬や猫の写真を飼い主さんに許可をもらって撮らせてもらおう。",
    icon: "🐶",
    category: "interaction",
  },
  {
    title: "「これ、何だろう？」を見つける",
    type: "探索",
    point: 60,
    level: "普通",
    timer: "30分",
    description: "「これ、何だろう？」と思うものを一つ見つけて、写真に撮ってみよう。",
    icon: "❓",
    category: "exploration",
  },
  {
    title: "工事現場を撮影する",
    type: "記録",
    point: 50,
    level: "簡単",
    timer: "15分",
    description: "街で見かけた工事現場を写真に撮って、未来の街を想像しよう。",
    icon: "🚧",
    category: "photo",
  },
  {
    title: "モノクロ写真に挑戦する",
    type: "記録",
    point: 70,
    level: "普通",
    timer: "30分",
    description: "街の風景をモノクロ写真で撮って、いつもと違う雰囲気を楽しもう。",
    icon: "⚫",
    category: "photo",
  },
];